---
- hosts: 127.0.0.1
  connection: local  
  tasks:
   - name: download Docker and Git
     command: apt-get install docker.io -y && apt-get install git -y

   - name: Checking and Cloning
     command: git --version && git clone https://github.com/dhemanth/Project.git

   - name: Docker execution
     shell: cd /opt/Project;service docker start;docker build -t project:v1 .

   - name: Run Docker image
     command: docker run --name project -itd -p 8090:80 project:v1 /bin/bash
     ignore_errors: yes

   - name: Attaching
     command: docker exec project /bin/bash -c 'rm -f /var/www/html/* ; sudo mv Project/webserver/* /var/www/html/. ; service apache2 restart'
